[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Prashik Jadhav", email = "prashikjadhav17@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.100.0",
    "ipaddress>=1.0.23",
    "pydantic>=2.0.0",
    "scapy>=2.5.0",
    "uvicorn[standard]>=0.23.0",
]

[project.scripts]
backend = "backend:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
